name: cesium-curated-content-samples-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - run: pnpm install
        working-directory: ../
      
      - run: pnpm build
        working-directory: ../
    

      